version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/solidjs/bare"
    schedule:
      interval: "weekly"
    groups:
      bare-deps:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/solidjs/tailwind"
    schedule:
      interval: "weekly"
    groups:
      tailwind-deps:
        patterns:
          - "*"
